# Generated by Django 4.2.7 on 2025-12-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeekdaySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("duration", models.IntegerField()),
                ("blink_count", models.IntegerField(default=0)),
                ("bad_posture_time", models.IntegerField(default=0)),
            ],
        ),
    ]
